apiVersion: v1
kind: Pod
metadata:
  labels:
    run: rainfall-pod
  name: rainfall-pod
  namespace: default
spec:
  containers:
  - image: 104466/rainfall-status:v2
    imagePullPolicy: Always
    name: rainfall-pod
    envFrom:
    - configMapRef:
        name: rainfall-config
