apiVersion: v1
kind: Service
metadata:
  labels:
    app: rainfall-svc
  name: rainfall-svc
spec:
  ports:
  - name: port
    nodePort: 30380
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: rainfall-dep
  type: NodePort
