FROM python:3.8-alpine

# Application directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy src code
COPY /app .

# Run application
CMD ["python", "main.py"]